# Cursor
env = HYPRCURSOR_THEME, Bibata-Modern-Classic
env = HYPRCURSOR_SIZE, 21
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 21

exec-once = hyprctl setcursor Bibata-Modern-Classic 21

